# Generated by Django 5.2.11 on 2026-02-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='temp_password',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
