# Generated by Django 5.2.11 on 2026-02-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpverification_temp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('ACTIVATION', 'Activation'), ('LOGIN', 'Login')], default='LOGIN', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='temp_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
