# Generated by Django 5.2.11 on 2026-02-07 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_stage', models.PositiveSmallIntegerField(choices=[(0, 'Not Started'), (1, 'Identity Verified'), (2, 'OTP Verified'), (3, 'Hostel Assigned'), (4, 'Biometric Registered'), (5, 'Registration Complete')], default=0)),
                ('hostel', models.CharField(max_length=100)),
                ('block', models.CharField(max_length=50)),
                ('room_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
